In [61]:
# Dependencies and Setup
import pandas as pd
import numpy as np


# Read data and store into a Pandas DataFrame
world_happiness_df = pd.read_csv("Resources/world-happiness-report.csv")
world_happiness_df.head()

,Country_name,year,Life_Ladder,Log_GDP_per_capita,Social_support,Healthy_life_expectancy_at_birth,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,Positive_affect,Negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [62]:
world_happiness_df = world_happiness_df.drop(["Positive_affect", "Negative_affect"], axis = 1)
world_happiness_df.head()

,Country_name,year,Life_Ladder,Log_GDP_per_capita,Social_support,Healthy_life_expectancy_at_birth,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776

In [63]:
world_happiness_df.rename(columns = {'Country_name': 'Country', 'year': 'Year', 'Life_Ladder': 'Happiness_Score', 'Log_GDP_per_capita': 'Economic_Production', 'Social_support': 'Social_Support', 'Healthy_life_expectancy_at_birth': 'Life_Expectancy', 'Freedom_to_make_life_choices': 'Freedom', 'Perceptions_of_corruption': 'Perceptions_of_Corruption'}, inplace = True)
world_happiness_df.head()

,Country,Year,Happiness_Score,Economic_Production,Social_Support,Life_Expectancy,Freedom,Generosity,Perceptions_of_Corruption
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776

In [64]:
world_happiness_df.dtypes

Country                       object
Year                           int64
Happiness_Score              float64
Economic_Production          float64
Social_Support               float64
Life_Expectancy              float64
Freedom                      float64
Generosity                   float64
Perceptions_of_Corruption    float64
dtype: object

In [65]:
world_happiness_df.to_csv('Cleaned_Data/World_Happiness_Report_All_Years.csv', index=False)

In [66]:
# Read data and store into a Pandas DataFrame
world_happiness_2021_df = pd.read_csv("Resources/world-happiness-report-2021.csv")
world_happiness_2021_df.head()

,Country_name,Regional_indicator,Ladder_score,Standard_error_of_ladder_score,upperwhisker,lowerwhisker,Logged_GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,Ladder_score_in_Dystopia,Explained_by_Log_GDP_per_capita,Explained_by_Social_support,Explained_by_Healthy_life_expectancy,Explained_by_Freedom_to_make_life_choices,Explained_by_Generosity,Explained_by_Perceptions_of_corruption,Dystopia_residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [67]:
world_happiness_2021_df.set_index('Country_name')
world_happiness_2021_df.head()

,Country_name,Regional_indicator,Ladder_score,Standard_error_of_ladder_score,upperwhisker,lowerwhisker,Logged_GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,Ladder_score_in_Dystopia,Explained_by_Log_GDP_per_capita,Explained_by_Social_support,Explained_by_Healthy_life_expectancy,Explained_by_Freedom_to_make_life_choices,Explained_by_Generosity,Explained_by_Perceptions_of_corruption,Dystopia_residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [68]:
world_happiness_2021_df = world_happiness_2021_df.drop(["Standard_error_of_ladder_score", "upperwhisker", "lowerwhisker", "Ladder_score_in_Dystopia", "Explained_by_Log_GDP_per_capita", "Explained_by_Social_support", "Explained_by_Healthy_life_expectancy", "Explained_by_Freedom_to_make_life_choices", "Explained_by_Generosity", "Explained_by_Perceptions_of_corruption", "Dystopia_residual"], axis = 1)
world_happiness_2021_df.head()

,Country_name,Regional_indicator,Ladder_score,Logged_GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,Western Europe,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,Western Europe,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,Western Europe,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,Western Europe,7.464,10.932,0.942,72.4,0.913,0.175,0.338

In [69]:
world_happiness_2021_df.rename(columns = {'Regional_indicator': 'World_Region', 'Country_name': 'Country', 'Ladder_score': 'Happiness_Score', 'Logged_GDP_per_capita': 'Economic_Production', 'Social_support': 'Social_Support', 'Healthy_life_expectancy': 'Life_Expectancy', 'Freedom_to_make_life_choices': 'Freedom', 'Perceptions_of_corruption': 'Perceptions_of_Corruption'}, inplace = True)
world_happiness_2021_df.head()

,Country,World_Region,Happiness_Score,Economic_Production,Social_Support,Life_Expectancy,Freedom,Generosity,Perceptions_of_Corruption
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,Western Europe,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,Western Europe,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,Western Europe,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,Western Europe,7.464,10.932,0.942,72.4,0.913,0.175,0.338

In [70]:
#world_happiness_2021_df['Year'] = world_happiness_2021_df.apply(lambda _: "2021", axis=1)
world_happiness_2021_df.insert(1, "Year", 2021)
world_happiness_2021_df.head()

,Country,Year,World_Region,Happiness_Score,Economic_Production,Social_Support,Life_Expectancy,Freedom,Generosity,Perceptions_of_Corruption
0,Finland,2021,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,2021,Western Europe,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,2021,Western Europe,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,2021,Western Europe,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,2021,Western Europe,7.464,10.932,0.942,72.4,0.913,0.175,0.338

In [71]:
world_happiness_2021_df.to_csv('Cleaned_Data/World_Happiness_Report_2021.csv', index=False)